field: 2bec25df-70fb-446d-85e7-84265abffea8 # Recipe Contents
fieldLayouts:
  31097a62-eba7-4d43-a194-ce58e7bd50c3:
    tabs:
      -
        elements:
          -
            fieldUid: d3428df1-2a59-4316-9b27-5b84ef3e9ba6 # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8195990b-f19a-4f31-a3e5-1b98054837ca
            warning: null
            width: 100
        name: Content
        uid: d2bae480-36ff-40d7-ab2e-0a6f405cba01
fields:
  d3428df1-2a59-4316-9b27-5b84ef3e9ba6: # Body Content
    columnSuffix: ikxlhefo
    contentColumnType: text
    fieldGroup: null
    handle: bodyContent
    instructions: null
    name: 'Body Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: recipeCopy
name: 'Recipe Copy'
sortOrder: 3
