field: 2bec25df-70fb-446d-85e7-84265abffea8 # Recipe Contents
fieldLayouts:
  23576b56-ffca-4021-bd42-c8e58ece4f69:
    tabs:
      -
        elements:
          -
            fieldUid: 0739007a-f898-4147-8244-a20652cbba5f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2adda5a-438b-4316-8102-4a75e6c0f275
            warning: null
            width: 100
          -
            fieldUid: 9b316ed4-9c69-4686-959b-039365b52aaa # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7133f8d2-25aa-4a35-a8f6-72004a6f822f
            warning: null
            width: 100
        name: Content
        uid: 66cf5919-e188-408b-b6cf-69a716d1a273
fields:
  9b316ed4-9c69-4686-959b-039365b52aaa: # Image Caption
    columnSuffix: fcfxqmqw
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: 'Image Caption'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0739007a-f898-4147-8244-a20652cbba5f: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:4e0d9b65-0771-4607-9430-fb2968d71a97' # Drinks
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4e0d9b65-0771-4607-9430-fb2968d71a97' # Drinks
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: recipeImage
name: 'Recipe Image'
sortOrder: 1
