field: 2bec25df-70fb-446d-85e7-84265abffea8 # Recipe Contents
fieldLayouts:
  e59f6e0f-6c51-47b2-8cf3-c2ff632011c5:
    tabs:
      -
        elements:
          -
            fieldUid: 7ded937d-9af6-4268-b3e8-b664692ca585 # Tip Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76ce9dd4-dcb3-4bd7-9f75-cc0687b5cdb5
            warning: null
            width: 100
        name: Content
        uid: 653d3a40-ba3f-473d-8b61-868870558067
fields:
  7ded937d-9af6-4268-b3e8-b664692ca585: # Tip Content
    columnSuffix: narcryug
    contentColumnType: text
    fieldGroup: null
    handle: tipContent
    instructions: null
    name: 'Tip Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeTip
name: 'Recipe Tip'
sortOrder: 2
