field: 2bec25df-70fb-446d-85e7-84265abffea8 # Recipe Contents
fieldLayouts:
  5aba65da-92f0-493d-a0c7-6e2c8443fd95:
    tabs:
      -
        elements:
          -
            fieldUid: e35cafc7-338e-4529-9f77-8f2e155c10f8 # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a997fd00-c0f6-4b7a-8537-450d90f55f04
            warning: null
            width: 100
          -
            fieldUid: 9546d007-a892-4779-8a67-ea55e74894bb # Steps Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c005d3f0-eddb-4450-9039-f5f70480654e
            warning: null
            width: 100
        name: Content
        uid: f2ebb2fa-c376-45ca-9e12-df6f58f17b7a
fields:
  9546d007-a892-4779-8a67-ea55e74894bb: # Steps Content
    columnSuffix: dxiblemj
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps Content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  e35cafc7-338e-4529-9f77-8f2e155c10f8: # Steps Title
    columnSuffix: ofskkoao
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
