fieldLayouts:
  b1edeaf2-9372-4334-89ff-65df92d80181:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b540217a-a463-43be-a0fc-7cd7e5674954
            warning: null
            width: 100
          -
            fieldUid: 3b7188c6-040f-4a25-aae0-373a0b7cd1ed # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f0c968f-b099-4e12-80cc-4f38eb0c9e7a
            warning: null
            width: 100
          -
            fieldUid: 7f3f0d3c-e37a-4fe4-b82f-d742dab3aae0 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f370ad0e-c605-4fed-b1d8-aeb6780cd268
            warning: null
            width: 100
          -
            fieldUid: 4d70a32c-8194-4cef-962c-5d9247d25c24 # Page Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db58e1ae-fbf8-414b-bb35-b087157e8365
            warning: null
            width: 100
        name: Content
        uid: 56bf293c-f570-4dcb-8963-00324e45c559
handle: default
hasTitleField: true
name: Default
section: 87a6ebec-65d9-447c-bd55-8ea6e5312cc3 # About Crafty Coffee
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
