fieldLayouts:
  004c4f36-2a35-4136-bff4-76c0bc4e077b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 80990eb6-2e85-407c-a289-940010588b38
            warning: null
            width: 100
          -
            fieldUid: 2d831a51-1c29-46dd-beb1-b1d4709fa14f # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d1181c9-9039-4e90-8ebd-8a6fa9a74baa
            warning: null
            width: 100
          -
            fieldUid: d2e1b3a3-71e2-459d-b3f8-0013d989580f # News Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f397bb61-c342-4480-8057-deff981d6df0
            warning: null
            width: 100
        name: Content
        uid: 9a354096-9584-42af-80e2-3b2b455a1a00
handle: default
hasTitleField: true
name: Default
section: 6c77b754-becc-40bc-848f-e660f2cb3892 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
