defaultPlacement: end
fieldLayouts:
  58a688f8-c146-4663-98d2-e1785920b13d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5feeb3e0-2cf6-4a58-9a76-f0a783d8352b
            warning: null
            width: 100
          -
            fieldUid: 05451c21-a706-4b8c-b916-0d1e79630294 # Style Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc1a95e9-4016-42ba-8413-a3d49ae379b3
            warning: null
            width: 100
        name: Content
        uid: 49e61cad-ba45-4ca0-9ccf-0e2de1feee31
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  7766dfc6-e337-4bb7-9993-43693df43814: # https://crafty-coffee.nitro
    hasUrls: true
    template: styles/_entry
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: null
  uid: 0cd6f358-35e2-427e-b018-cc540f662169
