columnSuffix: null
contentColumnType: string
fieldGroup: d7772fb0-3ec6-42c6-9a06-b029e5195dc0 # Drinks
handle: drinkRecipe
instructions: null
name: 'Drink Recipe'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add a drink recipe'
  showSiteMenu: false
  source: null
  sources:
    - 'section:89a62385-6ef7-4c89-81af-f5018c4a2602' # Recipes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
