columnSuffix: fjyrhcca
contentColumnType: text
fieldGroup: d7772fb0-3ec6-42c6-9a06-b029e5195dc0 # Drinks
handle: introduction
instructions: 'Short sentence at the top of the drinks page.'
name: Introduction
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
