defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  7766dfc6-e337-4bb7-9993-43693df43814: # https://crafty-coffee.nitro
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
